"""Seed data: all 41 participants from the AI Tester Blueprint 3x results page.

Names, projects, one-liners, repo URLs, and live-demo URLs are transcribed
verbatim from https://ai-tester-blueprint-3x-resultsandsu.vercel.app/. The
`tags`/`note` fields record what the consolidated platform absorbed from each
submission (mapped during the survey in docs/plan.md).
"""

from __future__ import annotations

from .models import Origin

ORIGINS: list[Origin] = [
    Origin(
        rank=1,
        name="P N V S Vivek",
        project="VIsionTestAI",
        one_liner="Autonomous multi-modal QA studio: interaction flows and DevTools recordings become POM classes, Playwright specs, and Cucumber BDD suites with visual self-healing.",
        repo="https://github.com/viveklabs-automation/vision-test-ai",
        live="https://vision-test-ai.onrender.com/",
        tags=["codegen", "execution", "failure-triage"],
        note="Failure-screenshot -> LLM locator patch -> rerun self-healing loop (cap 3 attempts) reused in E6.",
    ),
    Origin(
        rank=2,
        name="Tarun Babbar",
        project="QAE2E: AI-Powered QA Pipeline",
        one_liner="Six-agent pipeline from requirement to release confidence: test case generation, Playwright automation, execution, and an AI judge scoring and refining every step.",
        repo="https://github.com/TarunBabbar/AILearning/tree/main/qae2e",
        live="https://qae2e.vercel.app/",
        tags=["intake", "test-cases", "codegen", "execution", "release-gate"],
        note="RI->MT->AS->EX->DO->IQ pipeline with per-step LLM-as-judge is the spine E1-E11 follows; MCP surface planned (Phase 3).",
    ),
    Origin(
        rank=3,
        name="Sakshi Khandelwal",
        project="WorkPulse",
        one_liner="Adzuna Job API + AI job matching, explainable skill-gap analysis, and human-approved ATS resume optimization.",
        repo="https://github.com/sakshi-khandelwal02/3x-AI-Tester-Blueprint/tree/main/hackathon/workpulse",
        live="https://workpulse-delta-eight.vercel.app/",
        tags=["career"],
        note="Out of QA scope; evidence-based 'why match' scoring + human-approval gates inform the trust layer. Career companion planned (Phase 4).",
    ),
    Origin(
        rank=4,
        name="Shivani Singh",
        project="VERDICT",
        one_liner="Playwright failure intelligence: 20 deterministic rules establish what happened, AI interprets it, a guard verifies every claim is grounded in evidence.",
        repo="https://github.com/Shivani26Singh/verdict-playwright",
        live="https://verdict-playwright.vercel.app",
        tags=["failure-triage", "prompt-eval"],
        note="Evidence-pack + citation + deterministic Verdict Guard (G-rules) is the core of the trust layer and E6.",
    ),
    Origin(
        rank=5,
        name="Nitin Gawali",
        project="AI QA Detective",
        one_liner="Failure investigation: logs, stack traces, screenshots in -> scored root-cause analysis, regression tests, and release GO/NO-GO recommendation.",
        repo="https://github.com/nitingawali148/ai-qa-detective",
        live="https://ai-qa-detective-client-y1m3.vercel.app/",
        tags=["failure-triage", "release-gate", "codegen"],
        note="Provider-agnostic LLM layer with Zod-validated responses + offline mock is the llm_router pattern; risk rollup informs E11.",
    ),
    Origin(
        rank=6,
        name="Atish Mane",
        project="Playwright AI Studio",
        one_liner="Connects AI coding assistance to the live browser so broken locators are inspected and patched in place.",
        repo="https://github.com/atish53481/PlaywrightExt",
        live="https://playwright-ai-studio.vercel.app/",
        tags=["codegen", "execution", "failure-triage", "a11y"],
        note="In-browser DOM-aware generation/repair agents inform E4/E6; axe-core a11y assertions feed E8. Extension companion is a later stretch.",
    ),
    Origin(
        rank=7,
        name="Abhishek Raushan",
        project="TraceFix AI",
        one_liner="Diagnoses failing tests and noisy CI logs by clustering failures into real root causes, then a grounded diagnosis, confidence score, and production-ready fix.",
        repo="https://github.com/araushan2010143/AI-Tester-3X-Hackathon",
        live="https://tracefix-ai.vercel.app/",
        tags=["failure-triage", "prompt-eval"],
        note="Fingerprint clustering (N failures -> few diagnoses) + flaky analytics + multi-provider failover reused in E6.",
    ),
    Origin(
        rank=8,
        name="Niraj Mehta",
        project="QA Nexus AI",
        one_liner="Turns a spec (URL, PDF, Jira issue) into reviewable test cases and a runnable Playwright suite, grounding every selector against your real DOM and existing page objects.",
        repo="https://github.com/nirajmehta011/qa-nexus-ai",
        live="https://qa-nexus-ai-five.vercel.app",
        tags=["test-cases", "codegen", "execution", "intake"],
        note="Two-gate trust (grounding.json single-match locators + verify-suite real run) is the E4 grounding model.",
    ),
    Origin(
        rank=9,
        name="Chethan Dileep",
        project="TalentFlow AI",
        one_liner="End-to-end interview and candidate management platform tracking requirements, candidates, interviews, and hiring outcomes from a dashboard.",
        repo="https://github.com/Chethan21687/AI_3X_Tester_Hackathon",
        live="https://interview-tracker-ui-three.vercel.app/",
        tags=["talent"],
        note="Out of QA scope (talent platform); registry entry only.",
    ),
    Origin(
        rank=10,
        name="Sathish Kumar A S",
        project="QA Resume AI",
        one_liner="Evidence-grounded resume intelligence for QA professionals: verified-fact extraction, skill-coverage scoring, anti-hallucination rewrite validator.",
        repo="https://github.com/SathishQASelenium/resume-enhancer",
        live="https://resume-enhancer-delta.vercel.app",
        tags=["career", "prompt-eval"],
        note="Career companion later; 'LLM proposes, deterministic checker disposes' claim-check pattern informs the trust layer.",
    ),
    Origin(
        rank=11,
        name="Ashrith Panduranga Rao",
        project="Parity Scope",
        one_liner="AI vision model compares legacy vs. new UI screenshots to catch layout, data, and styling mismatches, returning a match score and Jira-ready bug write-ups.",
        repo="https://github.com/ashrithp1/parity-scope",
        live="https://parity-scope.vercel.app",
        tags=["visual"],
        note="Severity-tagged visual findings schema + one-click Jira export is the E7 module shape.",
    ),
    Origin(
        rank=12,
        name="Govind",
        project="QAGenX AI",
        one_liner="Helps teams analyze bugs, generate test cases, test APIs, understand failures, create test data, and automate repetitive QA workflows.",
        repo="https://github.com/govindbhe/QAgenX-Ai",
        live="https://qagenx-ai.vercel.app/",
        tags=["test-cases", "api-testing", "failure-triage"],
        note="Per-module typed pipeline (form -> route -> Zod schema -> rendered cards, safe fallback) informs engine structure; API scenario generator feeds E9.",
    ),
    Origin(
        rank=13,
        name="Nancy Bhardwaj",
        project="AssertPilot — MCP Agent QA & Security Observatory",
        one_liner="Tests what AI agents actually do: agent-execution observability, MCP/tool-call validation, prompt-injection testing, and risk classification.",
        repo="https://github.com/nancybhardwaj89/AssertPilot-MCP-Agent-QA-Security-Observatory",
        live="https://assert-pilot-mcp-agent-qa-security.vercel.app/",
        tags=["agent-security"],
        note="Expected-vs-actual trace validation + severity findings blueprint for the Agent/MCP Security Observatory (Phase 3).",
    ),
    Origin(
        rank=14,
        name="Virendra Patel",
        project="ATS Resume Builder",
        one_liner="Reads a resume and job description, surfaces missing ATS keywords/skills, and lets the user select which to add back.",
        repo="https://github.com/virendrapatel777/ATS_resume",
        live="https://ai-assisted-ats-resume-builder-5cqxwdrjh.vercel.app/",
        tags=["career"],
        note="Career companion later; human-in-the-loop gap selection pattern informs approval gates.",
    ),
    Origin(
        rank=15,
        name="Parag Waghmare",
        project="EDI File Generator & Validator",
        one_liner="Generates and validates EDI files automatically across transaction families.",
        repo="https://github.com/waghmareparag222-debug/Hackthon_AI_3X",
        live="https://hackthon-ai-3-x.vercel.app/",
        tags=["etl"],
        note="Deterministic generate-then-validate domain engine informs E10's format-QA side.",
    ),
    Origin(
        rank=16,
        name="Mrutyunjay Mallik",
        project="Release Risk Analysis",
        one_liner="Analyzes pass/fail/abort results by component and priority, visualizes them, and supports Go/No-Go release decisions with configurable thresholds.",
        repo="https://github.com/mmk012ai/ReleaseRiskAnalysis",
        live="https://release-risk-analysis.vercel.app/",
        tags=["release-gate"],
        note="Configurable decision-rule layer (criteria -> GO/NO-GO with stated evidence) is E11.",
    ),
    Origin(
        rank=17,
        name="Dhanashree",
        project="QA_AI_Solution",
        one_liner="End-to-end QA agent: PRD upload, scenario/case generation, Playwright execution, Jira defect logging, emailed results report.",
        repo="https://github.com/nroy222/AI-Tester-3X-Hackathon",
        live="https://qa-ai-solution.vercel.app/",
        tags=["intake", "test-cases", "codegen", "execution", "release-gate"],
        note="Orchestratable step pipeline with per-step visibility informs the E1-E11 workflow skeleton.",
    ),
    Origin(
        rank=18,
        name="Kalpesh Pingale",
        project="Requirements to Test Gap Analyzer",
        one_liner="Identifies gaps between written requirements and existing test coverage with a traceability matrix.",
        repo="https://github.com/Kalpesh-Pingale/RequirementsToTestGapAnalyzer",
        live="https://requirements-to-test-gap-analyzer.vercel.app/",
        tags=["requirement-doctor", "test-cases"],
        note="Local score recompute (never trusted to model) + FULL/PARTIAL/NONE/AMBIGUOUS verdicts inform E2/E3 coverage verdicts.",
    ),
    Origin(
        rank=19,
        name="Dheeraj Reddy",
        project="OmnyGO",
        one_liner="Turns plain-English test descriptions into real browser tests: plans steps, drives a live Chromium browser, verifies the goal was achieved.",
        repo="https://github.com/deeraj-pw/omnygo-vercel",
        live="https://omnygo-vercel.vercel.app",
        tags=["execution", "failure-triage"],
        note="Planner/driver/verifier split + human-in-the-loop credential stops + independent verification inform E5 and the NL-browser-agent stretch.",
    ),
    Origin(
        rank=20,
        name="Archana Nathe",
        project="TestSense AI",
        one_liner="Transforms requirements into an execution-ready testing strategy: scenarios, detailed cases, negative/edge/security cases, and coverage-gap detection.",
        repo="https://github.com/Archana35-stack/testsense-ai",
        live="https://testsense-ai-nine.vercel.app",
        tags=["requirement-doctor", "test-cases"],
        note="Test-case record schema with execution-type recommendation fields (Automate/Manual/Both) informs the canonical TestCase model (E3).",
    ),
    Origin(
        rank=21,
        name="Rohit Mane",
        project="Visual Regression QA Coach",
        one_liner="Compares before/after screenshots, flags likely UI regressions, and recommends whether a change is safe to ship.",
        repo="https://github.com/RRMANE/AI_Project_16_Aug",
        live="https://visual-regression-qa-coach.vercel.app",
        tags=["visual"],
        note="Optional-LLM-over-deterministic-heuristic-fallback + ship/don't-ship verdict informs E7.",
    ),
    Origin(
        rank=22,
        name="Shashank Verma",
        project="TestCaseAI — Jira Story to Test Case Generator",
        one_liner="Connects to Jira, reads user stories, and auto-generates structured test cases exportable to CSV, Excel, JSON, PDF, TestRail, or Azure DevOps.",
        repo="https://github.com/shashankver/Test-Case-Generator/",
        live="https://testcase-ai-henna.vercel.app/#dashboard",
        tags=["intake", "test-cases"],
        note="One canonical test-case model fanning out to many exporters is the export-adapter layer design.",
    ),
    Origin(
        rank=23,
        name="Manish Mishra",
        project="QA Workflow Dashboard",
        one_liner="Centralized workspace guiding QA through story analysis, planning, exploratory testing, automation, execution, self-healing, and reporting.",
        repo="https://github.com/mmanish2004/Hackathon",
        live="https://qaworkflow-tau.vercel.app/",
        tags=["failure-triage", "release-gate"],
        note="Approval-gated 6-stage workflow + failure taxonomy with guardrails is a UX reference for the platform's human-in-the-loop layer. No code merged.",
    ),
    Origin(
        rank=24,
        name="Sankar Cheerala",
        project="AI Testcase Generator",
        one_liner="Generates test cases directly from Jira and GitHub issues with a deterministic, traceable output contract.",
        repo="https://github.com/Cheeras/AITesters3xHackthon",
        live="https://ai-testers3x-hackthon-two.vercel.app/",
        tags=["intake", "test-cases"],
        note="Deterministic output contract (stable CSV columns, no invention, 'Insufficient information to determine.') is the E3 rigor standard.",
    ),
    Origin(
        rank=25,
        name="Dhanush Chikkamade Gowda",
        project="SpecCraft AI",
        one_liner="Ingests visual bug screenshots and uses multimodal vision models to synthesize Playwright regression code, Jira tickets, GitHub Issues, and root-cause diagnostics.",
        repo="https://github.com/dhanush-blr/speccraft-ai",
        live="https://speccraft-ai-five.vercel.app/",
        tags=["codegen", "visual", "failure-triage"],
        note="Screenshot -> verified facts -> gap analysis -> artifacts (selectors marked 'Inference — verify') pipeline informs E7 + E4 vision intake.",
    ),
    Origin(
        rank=26,
        name="Om Gutty",
        project="QAGuard AI",
        one_liner="Transforms requirements into governed, traceable testing artifacts with a human approving every step before anything ships to automation.",
        repo="https://github.com/omgutty/qaguard-ai",
        live="https://qaguard-ai.vercel.app/",
        tags=["requirement-doctor", "test-cases", "codegen", "release-gate"],
        note="Five-agent pipeline with typed contracts + approve/reject gates is the governance skeleton for approval gates across the platform.",
    ),
    Origin(
        rank=27,
        name="Patel Vishesh Asheshkumar",
        project="QA API Agent",
        one_liner="Combines single API execution, AI-powered analysis, Excel-based bulk test runs, and instant shareable reporting.",
        repo="https://github.com/Vishesh9Patel/VIshesh_Patel_QA_API_Agent_Hackarthon",
        live="https://v-ishesh-patel-qa-api-agent-hackarthon-5oyrb1j2f-study-1800.vercel.app/",
        tags=["api-testing"],
        note="Risk-scoring + test-gap detection in front of real API execution + shareable reports is the E9 shape.",
    ),
    Origin(
        rank=28,
        name="Namrata Roy",
        project="Jira Integrated RAG Explorer",
        one_liner="Ingests a Jira ticket, embeds its content, and answers analysis or test-case questions strictly from that ticket via a visible retrieve-then-generate pipeline.",
        repo="https://github.com/Chimni108/AITesterBlueprint3x/tree/main/Hackathon",
        live="https://jira-rag-app.vercel.app/",
        tags=["rag"],
        note="Visible, hand-editable RAG pipeline (browse chunks, tune top-K, regenerate) is the transparency model for the RAG Explorer (Phase 3).",
    ),
    Origin(
        rank=29,
        name="Paritosh Panigrahi",
        project="Test Generation App",
        one_liner="Generates Playwright automation tests and structured manual test cases from a requirement, URL, codebase, PRD, Jira ticket, or Confluence page.",
        repo="https://github.com/paritoshpanigrahi/AITesterBluePrint3X",
        live="https://ai-tester-blue-print3-x-one.vercel.app/",
        tags=["intake", "test-cases", "codegen", "execution"],
        note="Locator -> plan -> generate -> heal agent chain + registry-based duplicate detection informs E4 automation loop.",
    ),
    Origin(
        rank=30,
        name="Khan Bilal",
        project="AI Requirement Doctor",
        one_liner="Diagnoses requirement defects (ambiguity, incompleteness, inconsistency) and confirms fixes before producing an enhanced, testable rewrite.",
        repo="https://github.com/kbilal3940/ai-requirement-doctor",
        live="https://ai-requirement-doctor-fe.onrender.com",
        tags=["requirement-doctor"],
        note="Diagnose -> confirm -> enhance loop with a quantified requirement-quality score is E2.",
    ),
    Origin(
        rank=31,
        name="Guruprasad Shrinivas Ganiga",
        project="TestPlanBuddy",
        one_liner="Test-case creation tool built around the B.L.A.S.T framework, demonstrated against a sample enhancement story.",
        repo="https://github.com/Guruprasad-Shrinivas/AI-Tester-Blueprint-3x/tree/AI-Tester-Blueprint-3x/Chapter_3(a)_B.L.A.S.T_FrameWork-TestCaseCreation",
        live="https://testplanbuddy-delta.vercel.app",
        tags=["test-cases"],
        note="B.L.A.S.T. 'deterministic tools + LLM as navigator' process spec informs E3 prompt/governance scaffold.",
    ),
    Origin(
        rank=32,
        name="Ishank Walia",
        project="OTT DRM AI Troubleshooting Copilot",
        one_liner="Diagnoses OTT playback and DRM failures using deterministic rules and Pinecone-powered RAG, ranking probable root causes and exporting diagnosis reports as PDFs.",
        repo="https://github.com/ishankwalia398/AI-Projects/tree/main/Project_12_(OTT_DRM_AI_Troubleshooting_Copilot)/OTT-DRM-AI-Troubleshooting-Copilot",
        live="https://ott-drm-copilot.vercel.app/",
        tags=["failure-triage", "rag"],
        note="Rules-first weighted diagnosis with optional LLM explanation is an anti-hallucination exemplar for troubleshooters.",
    ),
    Origin(
        rank=33,
        name="Kiranmai Wunnava Venkata",
        project="ETL QA Buddy",
        one_liner="Turns plain-English QA rules into runnable pytest tests against a sample ETL database, with pass/fail results, a schema explorer, and an 18-test regression suite.",
        repo="https://github.com/kiranmaiwv/AITesterBlueprint3x/tree/main/ETL_QA_Buddy/ETL_QA_Buddy",
        live="https://etl-qa-buddy.vercel.app/",
        tags=["etl", "execution"],
        note="Prompt-time schema injection + sandboxed execution of AI-generated tests against a seeded defect DB is E10's closed loop.",
    ),
    Origin(
        rank=34,
        name="Rohan Deo",
        project="QA Helper",
        one_liner="Connects with Jira, Confluence, and an LLM to generate QA artifacts and analyze missed defects.",
        repo="https://github.com/rrdeo/ai-native-qa-engineering-workspace",
        live="https://rdeo-qa.vercel.app",
        tags=["test-cases", "leakage"],
        note="Defect Leakage Analyzer (missed-defect classification + preventive-test feedback) is E12.",
    ),
    Origin(
        rank=35,
        name="Gurpreet Singh",
        project="AI Test Case Generator Buddy",
        one_liner="Analyzes real Jira stories, design documents, and UI/Figma screenshots to generate structured test cases covering functional, UI, security, and accessibility scenarios.",
        repo="https://github.com/Gurpreet-it/AI-Test/tree/main/Guru-WorkSpace/Test-Case-Generator",
        live="https://gurpreetproject-guru-0ebe.vercel.app",
        tags=["intake", "test-cases"],
        note="Client-side image compression + evidence-only prompting makes vision inputs viable inside serverless limits.",
    ),
    Origin(
        rank=36,
        name="Narayan Boolchandani",
        project="Fantasy Team Builder",
        one_liner="A fantasy sports team-builder app built for the hackathon.",
        repo="https://github.com/narayanb24/Fantasy-Team-Builder-v2",
        live="https://fantasy-team-builder-v2.vercel.app/",
        tags=["unrelated"],
        note="Unrelated to QA; registry entry only, no code merged.",
    ),
    Origin(
        rank=37,
        name="Rekha Govardhanan",
        project="AI QA Copilot",
        one_liner="Transforms requirements into test plans, test cases, coverage analysis, bug triage, and test closure summaries.",
        repo="https://github.com/govardhanrekha/AI-QA-COPILOT",
        live="https://ai-qa-copilot-3x3kyu75y-govardhanrekhas-projects.vercel.app/",
        tags=["requirement-doctor", "test-cases", "release-gate"],
        note="Chained requirement-doc-in -> all-artifacts-out model with traceability IDs carried through stages informs the E1-E11 workflow spine.",
    ),
    Origin(
        rank=38,
        name="Deerasameera.Ch",
        project="AIQAEngineer Agent",
        one_liner="An AI QA engineering agent: requirement normalization, quality gates, test design, Playwright/Bruno codegen, live execution, human-gated self-healing, audit report + Jira bug creation.",
        repo="https://github.com/chdeerasameera-dev/AITesterBlueprint3x",
        live="https://aiqaengineer-deera-s-projects.vercel.app",
        tags=["requirement-doctor", "codegen", "execution", "failure-triage", "release-gate"],
        note="Dual rule-gate + LLM-gate before generation/execution and human-approval self-healing inform the platform's gates.",
    ),
    Origin(
        rank=39,
        name="Sujan Mahapatra",
        project="Prompt Testing",
        one_liner="A tool for testing prompts against different evaluation criteria.",
        repo="https://github.com/sujanmahapatra/Prompt_Testing",
        live="https://prompt-testing-huk4-31yn4v06t-learning-938c.vercel.app",
        tags=["prompt-eval"],
        note="Golden-set + LLM-as-judge assertion harness is the Prompt-Eval layer the platform runs over its own prompts (CI).",
    ),
    Origin(
        rank=40,
        name="Aradhana Mahanta",
        project="Accessibility Copilot Analyzer",
        one_liner="Analyzes pages for accessibility issues (missing labels, contrast problems, keyboard traps) and suggests fixes using WCAG 2.0/2.1 guidelines.",
        repo="https://github.com/Aradhana1016/AI-Tester-3x-Hackathon",
        live="https://ai-tester-3x-hackathon-pkr0siw5j-test-automation-tester.vercel.app",
        tags=["a11y"],
        note="Standards-enumerable checker + WCAG-conformant fix suggestions is the E8 engine shape.",
    ),
    Origin(
        rank=41,
        name="Shashikala",
        project="TestNexus AI",
        one_liner="Enterprise-grade QA automation platform generating test cases from Jira requirements, plus Playwright generation, failure analysis, and defect reporting via OpenAI/Groq.",
        repo="https://github.com/shashi-git123/AiLearning-Shashi/",
        live="https://frontend-1hbkbc0qq-shashi-s-projects20.vercel.app",
        tags=["unverifiable"],
        note="Survey found the repo's reachable content does not match the pitch (no Jira/Playwright/LLM code located); credited as listed, code not merged.",
    ),
]
